"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { supabase, supabaseConfigured } from "@/lib/supabase";

type Evolution = "Flareon" | "Vaporeon" | "Jolteon" | "Espeon" | "Umbreon" | "Leafeon" | "Glaceon" | "Sylveon";
type Capture = { id:number; name:string; rarity:"Normal"|"Especial"|"Legendario"; sprite:string; value:number; recordId?:string };
type Player = { id: string; dbId?:string; name: string; evolution?: Evolution; level: number; xp: number; energy: number; tokens: number; route: string[]; captures: Capture[]; arenaEvents?: string[]; evolvedShown?: boolean };
type Station = { id: string; title: string; kind: "trainer" | "rocket"; area: string; reward: number; color: string };
const GAME_OPENS_AT = new Date("2026-08-29T17:00:00+02:00").getTime();
const TEST_MODE = true;

const stations: Station[] = [...[
  ["trainer-1","Ciudad Plateada","Gimnasio de Roca",2,"violet"],["trainer-2","Ciudad Celeste","Gimnasio de Agua",2,"orange"],["trainer-3","Ciudad Carmín","Gimnasio Eléctrico",2,"mint"],["trainer-4","Ciudad Azulona","Gimnasio de Planta",2,"blue"],["trainer-5","Ciudad Fucsia","Gimnasio de Veneno",2,"pink"],["trainer-6","Ciudad Azafrán","Gimnasio Psíquico",2,"yellow"],["trainer-7","Isla Canela","Gimnasio de Fuego",2,"violet"],["trainer-8","Ciudad Verde","Gimnasio de Tierra",2,"orange"],
].map(([id,title,area,reward,color]) => ({ id: String(id), title: String(title), kind: "trainer" as const, area: String(area), reward: Number(reward), color: String(color) })), ...[
  ["rocket-1","Monte Moon","Guarida Team Rocket"],["rocket-2","Casino Rocket","Guarida Team Rocket"],["rocket-3","Silph S.A.","Guarida Team Rocket"],["rocket-4","Ruta Victoria","Guarida Team Rocket"],
].map(([id,title,area]) => ({ id, title, kind: "rocket" as const, area, reward: 3, color: "red" }))];

const eeveelutions: {name: Evolution; type: string; perk: string; image: string}[] = [
  {name:"Flareon",type:"Fuego",perk:"Un segundo intento una vez por combate",image:"136"}, {name:"Vaporeon",type:"Agua",perk:"Recuperación extra en Centro Pokémon",image:"134"},
  {name:"Jolteon",type:"Eléctrico",perk:"Pista rápida en códigos",image:"135"}, {name:"Espeon",type:"Psíquico",perk:"Pista en lógica y deducción",image:"196"},
  {name:"Umbreon",type:"Siniestro",perk:"Menor pérdida de energía al fallar",image:"197"}, {name:"Leafeon",type:"Planta",perk:"Pista en retos visuales",image:"470"},
  {name:"Glaceon",type:"Hielo",perk:"Descarta una respuesta errónea",image:"471"}, {name:"Sylveon",type:"Hada",perk:"Ventaja especial en Team Rocket",image:"700"},
];
const questions = [
  {tier:1, prompt:"¿Qué número falta? 3 · 8 · 15 · 24 · ?", options:["32","33","35","37"], answer:2, label:"Golpe patrón"},
  {tier:1, prompt:"Todos los flanes son postres. Algunos postres son fríos. ¿Qué podemos asegurar?", options:["Todos los flanes son fríos","Algunos flanes son fríos","Los flanes son postres","Nada"], answer:2, label:"Lectura precisa"},
  {tier:1, prompt:"En el código César, retroceder 3 letras convierte 'FDVD' en…", options:["CASA","CAMA","DADA","BABA"], answer:0, label:"Descifrado"},
  {tier:2, prompt:"Un reloj marca las 15:15. ¿Qué ángulo menor forman sus agujas?", options:["0°","7,5°","15°","30°"], answer:1, label:"Cálculo fino"},
  {tier:2, prompt:"Ana llega antes que Bruno. Bruno antes que Carla. Diego llega antes que Ana. ¿Quién llega primero?", options:["Ana","Bruno","Carla","Diego"], answer:3, label:"Ruta lógica"},
  {tier:2, prompt:"Tienes 8 bolas idénticas; una pesa más. Con una balanza, ¿cuántas pesadas bastan como mínimo?", options:["1","2","3","4"], answer:1, label:"Estrategia"},
  {tier:3, prompt:"Hay tres cajas: 'rojas', 'azules' y 'mezcladas'. Todas las etiquetas son falsas. Sacas una ficha de una caja. ¿De cuál debes sacar para deducirlo todo?", options:["Rojas","Azules","Mezcladas","Da igual"], answer:2, label:"Deducción"},
  {tier:3, prompt:"Un padre tiene cuatro hijas; cada hija tiene un hermano. ¿Cuántos hijos tiene en total?", options:["4","5","8","9"], answer:1, label:"Trampa limpia"},
  {tier:3, prompt:"Dos cuerdas tardan una hora en consumirse, de manera irregular. ¿Cómo mides 45 minutos?", options:["Cortando una en cuatro","Encendiendo ambas por un extremo","Una por ambos extremos y la otra por un extremo; al acabar la primera, enciendes el otro extremo de la segunda","No se puede"], answer:2, label:"Plan maestro"},
  {tier:4, prompt:"Solo una afirmación es cierta. A: 'B miente'. B: 'C miente'. C: 'A y B mienten'. ¿Quién dice la verdad?", options:["A","B","C","Nadie"], answer:1, label:"Lógica élite"},
  {tier:4, prompt:"En ajedrez, si tu rey está en jaque, ¿cuál de estas NO es una respuesta legal?", options:["Mover el rey","Capturar la pieza atacante","Bloquear el ataque si es una línea","Hacer jaque al rey rival ignorando el tuyo"], answer:3, label:"Defensa real"},
  {tier:4, prompt:"Cuatro personas cruzan un puente de noche en 1, 2, 7 y 10 minutos. Solo caben dos y hay una linterna. ¿Tiempo mínimo?", options:["17","19","20","21"], answer:0, label:"Estrategia élite"},
];
const playerNames = ["Eduardo","Karim","Carlos de la Fuente","Cristian","Nicole","Ros","María Santana","María Alfonso","Lola","Ismael","Marco","Alex","María Loufoukou"];
const defaultPlayers: Player[] = [
  { id:"alejandro", name:"Alejandro", level:1, xp:20, energy:100, tokens:0, route:[], captures:[], arenaEvents:[] },
  ...playerNames.map((name, index) => ({ id:`jugador-${index+1}`, name, level:1, xp:0, energy:100, tokens:0, route:[], captures:[], arenaEvents:[] })),
];
const menu = [{label:"Cerveza",cost:2},{label:"Chupito",cost:3},{label:"Cubata",cost:6},{label:"Extra de barbacoa",cost:4}];
const journeyIds = ["trainer-1","rocket-1","trainer-2","trainer-3","trainer-4","rocket-2","trainer-5","trainer-6","rocket-3","trainer-7","trainer-8","rocket-4"];
const payaStops = ["trainer-2","trainer-5","trainer-7"];
const dexPool: Capture[] = [
  {id:25,name:"Pikachu",rarity:"Normal",sprite:"25",value:1},{id:4,name:"Charmander",rarity:"Normal",sprite:"4",value:1},{id:7,name:"Squirtle",rarity:"Normal",sprite:"7",value:1},{id:1,name:"Bulbasaur",rarity:"Normal",sprite:"1",value:1},{id:133,name:"Eevee",rarity:"Normal",sprite:"133",value:1},{id:52,name:"Meowth",rarity:"Normal",sprite:"52",value:1},{id:143,name:"Snorlax",rarity:"Especial",sprite:"143",value:2},{id:94,name:"Gengar",rarity:"Especial",sprite:"94",value:2},{id:149,name:"Dragonite",rarity:"Especial",sprite:"149",value:2},{id:6,name:"Charizard",rarity:"Especial",sprite:"6",value:2},{id:150,name:"Mewtwo",rarity:"Legendario",sprite:"150",value:4},{id:151,name:"Mew",rarity:"Legendario",sprite:"151",value:4},{id:144,name:"Articuno",rarity:"Legendario",sprite:"144",value:4},{id:145,name:"Zapdos",rarity:"Legendario",sprite:"145",value:4},{id:146,name:"Moltres",rarity:"Legendario",sprite:"146",value:4}
];

export default function Home() {
  const [players, setPlayers] = useState<Player[]>(defaultPlayers);
  const [activeId, setActiveId] = useState("");
  const [screen, setScreen] = useState<"select"|"partner"|"waiting"|"evolution"|"home"|"pokedex"|"route"|"scan"|"arena"|"team"|"admin">("select");
  const [station, setStation] = useState<Station | null>(null);
  const [answer, setAnswer] = useState<number | null>(null);
  const [message, setMessage] = useState("");
  const [adminTarget, setAdminTarget] = useState("alejandro");
  const [arenaOpponent, setArenaOpponent] = useState("");
  const [arenaChallenge, setArenaChallenge] = useState("");
  const [pendingStation, setPendingStation] = useState<Station | null>(null);
  const [playerCardCode, setPlayerCardCode] = useState("");
  const [teamMate, setTeamMate] = useState("");
  const [manualCode, setManualCode] = useState("");
  const [cameraOpen, setCameraOpen] = useState(false);
  const videoRef = useRef<HTMLVideoElement>(null);
  const scanTimerRef = useRef<number | null>(null);
  const [loaded, setLoaded] = useState(false);
  const [now, setNow] = useState(Date.now());

  async function loadGame(){
    if(!supabase){setLoaded(true);return;}
    const [profilesResult,progressResult,capturesResult]=await Promise.all([
      supabase.from("profiles").select("*"),
      supabase.from("game_progress").select("player_id,station_id"),
      supabase.from("captures").select("*").is("redeemed_at",null),
    ]);
    if(profilesResult.error){setMessage("No se ha podido conectar con Supabase. Se mantiene el modo local.");setLoaded(true);return;}
    const rows=profilesResult.data??[];const progress=progressResult.data??[];const captures=capturesResult.data??[];
    const next:Player[]=rows.map((row)=>({id:row.player_code,dbId:row.id,name:row.display_name,evolution:row.evolution||undefined,level:row.level,xp:row.xp,energy:row.energy,tokens:row.tokens,route:progress.filter((item)=>item.player_id===row.id).map((item)=>item.station_id),captures:captures.filter((item)=>item.player_id===row.id).map((item)=>({recordId:item.id,id:item.pokemon_id,name:item.pokemon_name,rarity:item.rarity as Capture["rarity"],sprite:item.sprite_id,value:item.token_value})),arenaEvents:[]}));
    const ordered=defaultPlayers.map((seed)=>next.find((item)=>item.id===seed.id)??seed);
    setPlayers(ordered);localStorage.setItem("liga27-players-v3",JSON.stringify(ordered));setLoaded(true);
  }

  useEffect(() => { const stored=localStorage.getItem("liga27-players-v3"); if(stored) { const restored=JSON.parse(stored).map((p:Player)=>({...p,captures:(p.captures||[]).map((c:Capture|string)=>typeof c==="string"?{id:0,name:c,rarity:"Normal",sprite:"25",value:1}:c),arenaEvents:p.arenaEvents||[]})); setPlayers(restored); } const savedActive=localStorage.getItem("liga27-active-player"); if(savedActive) setActiveId(savedActive); const params=new URLSearchParams(location.search); const qr=params.get("qr"); const card=params.get("player"); const found=stations.find((item)=>item.id===qr); if(found) setStation(found); if(qr==="arena") setScreen("arena"); if(card) { setPlayerCardCode(card); setMessage("Tarjeta de entrenador detectada. Elige tu perfil y abre la Arena o Team Rocket."); } if(qr==="alto-mando") setMessage("El Alto Mando se desbloquea al completar las 12 capturas de ruta."); void loadGame(); const channel=supabase?.channel("liga-27-live").on("postgres_changes",{event:"*",schema:"public"},()=>{void loadGame();}).subscribe(); return()=>{if(channel&&supabase)void supabase.removeChannel(channel);}; }, []);
  useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer);},[]);
  useEffect(()=>{const teammate=players.find((player)=>player.id===teamMate);if(!supabase||!activeId||!teammate?.dbId)return;const sender=players.find((player)=>player.id===activeId);if(!sender?.dbId)return;void supabase.from("team_invites").insert({from_player_id:sender.dbId,to_player_id:teammate.dbId,station_id:pendingStation?.id??null,status:"pending"});},[teamMate]);
  const active = useMemo(()=>players.find((p)=>p.id===activeId) ?? players[0],[players,activeId]);
  const target = useMemo(()=>players.find((p)=>p.id===adminTarget) ?? players[0],[players,adminTarget]);
  const complete=active.route.length; const finalUnlocked=complete===stations.length;
  const isOpen=TEST_MODE || now>=GAME_OPENS_AT;
  const remaining=Math.max(0,GAME_OPENS_AT-now);
  const countdown={days:Math.floor(remaining/86400000),hours:Math.floor((remaining%86400000)/3600000),minutes:Math.floor((remaining%3600000)/60000),seconds:Math.floor((remaining%60000)/1000)};
  const persist=(next:Player[])=>{const changed=next.find((player,index)=>{const previous=players[index];return previous&&(player.evolution!==previous.evolution||player.level!==previous.level||player.xp!==previous.xp||player.energy!==previous.energy||player.tokens!==previous.tokens);});setPlayers(next);localStorage.setItem("liga27-players-v3",JSON.stringify(next));if(changed?.dbId&&supabase)void supabase.from("profiles").update({evolution:changed.evolution??null,level:changed.level,xp:changed.xp,energy:changed.energy,tokens:changed.tokens,updated_at:new Date().toISOString()}).eq("id",changed.dbId);};
  const patchActive=(patch:Partial<Player>)=>persist(players.map((p)=>p.id===activeId?{...p,...patch}:p));
  const difficulty=Math.min(4,Math.floor(active.route.length/3)+1);
  const tierQuestions=questions.filter((item)=>item.tier===difficulty);
  const question=station?tierQuestions[(stations.findIndex((item)=>item.id===station.id)+active.name.length)%tierQuestions.length]:null;
  const chosenEvolution=eeveelutions.find((item)=>item.name===active.evolution);
  const evolved=active.route.length>=4&&active.evolution?active.evolution:"Eevee";
  const companionImage=evolved==="Eevee"?"133":chosenEvolution?.image ?? "133";

  function startStation(next:Station){ if(!isOpen){setScreen("waiting");return;} if(active.route.includes(next.id)){setMessage("Este entrenador ya está superado en tu ruta.");return;} if(payaStops.includes(next.id)&&!active.arenaEvents?.includes(next.id)){setPendingStation(next);setArenaChallenge("");setScreen("arena");setMessage("¡Aparece la Arena de Payá antes del combate!");return;} if(next.kind==="rocket"&&!teamMate){setPendingStation(next);setScreen("team");setMessage("Team Rocket requiere que enlaces una tarjeta de entrenador.");return;} setAnswer(null);setMessage("");setStation(next); }
  function chooseEvolution(evolution: Evolution){patchActive({evolution});setScreen(isOpen?"home":"waiting");}
  function setPlayerEvolution(playerId:string, evolution:Evolution){persist(players.map((player)=>player.id===playerId?{...player,evolution}:player));setMessage(`Evolución actualizada.`);}
  function randomCapture(){ const roll=Math.random()*100; const pool=dexPool.filter((p)=>p.rarity=== (roll<4?"Legendario":roll<27?"Especial":"Normal")); return pool[Math.floor(Math.random()*pool.length)]; }
  function resolveBattle(){ if(!station||answer===null||!question)return; if(answer!==question.answer){ const loss=active.evolution==="Umbreon"?15:25; const energy=Math.max(0,active.energy-loss);patchActive({energy});setMessage(energy===0?"¡Tu compañero ha quedado debilitado! Ve a Alejandro para recuperarte.":`El rival contraataca. Pierdes un ${loss}% de energía.`);return;} const route=[...active.route,station.id];const xp=active.xp+25;const capture={...randomCapture(),recordId:crypto.randomUUID()};patchActive({route,tokens:active.tokens+station.reward,xp,level:Math.max(1,Math.floor(xp/100)+1),captures:[...active.captures,capture]});if(supabase&&active.dbId){void supabase.from("game_progress").insert({player_id:active.dbId,station_id:station.id});void supabase.from("captures").insert({id:capture.recordId,player_id:active.dbId,pokemon_id:capture.id,pokemon_name:capture.name,rarity:capture.rarity,sprite_id:capture.sprite,token_value:capture.value});}setMessage(`¡Rival derrotado! ${capture.rarity==="Legendario"?"¡UNA CAPTURA LEGENDARIA! ":""}Has capturado a ${capture.name}. +${station.reward} tokens.`); }
  function cashCapture(index:number){ const capture=active.captures[index]; if(!capture)return; patchActive({captures:active.captures.filter((_,i)=>i!==index),tokens:active.tokens+capture.value}); if(supabase&&capture.recordId)void supabase.from("captures").update({redeemed_at:new Date().toISOString()}).eq("id",capture.recordId);setMessage(`${capture.name} canjeado por ${capture.value} token${capture.value>1?"s":""}.`); }
  function beginArena(){ const opponent=players.find((p)=>p.id===arenaOpponent); if(!opponent){setMessage("Escanea o introduce la tarjeta de tu contrincante primero.");return;} if(!arenaChallenge){setMessage("Elige el reto de la Arena.");return;} if(supabase&&active.dbId&&opponent.dbId)void supabase.from("arena_matches").insert({player_one_id:active.dbId,player_two_id:opponent.dbId,challenge:arenaChallenge,reward_tokens:2});const eventId=pendingStation?.id; if(eventId) {patchActive({arenaEvents:[...(active.arenaEvents||[]),eventId]}); setMessage(`Arena superada. El ganador recibe +2 tokens en el Centro Pokémon. Ahora toca ${pendingStation?.title}.`); setTimeout(()=>{const go=pendingStation;setPendingStation(null);setScreen("home");if(go){setAnswer(null);setMessage("");setStation(go);}},1000);return;} setMessage(`Reto confirmado contra ${opponent.name}: ${arenaChallenge}. Alejandro decide el ganador y concede +2 tokens.`); }
  function redeem(item:(typeof menu)[number]){if(target.tokens<item.cost){setMessage(`${target.name} no tiene tokens suficientes.`);return;}persist(players.map((p)=>p.id===target.id?{...p,tokens:p.tokens-item.cost}:p));if(supabase&&target.dbId)void supabase.from("redemptions").insert({player_id:target.dbId,item_name:item.label,token_cost:item.cost});setMessage(`Canje confirmado: ${item.label} para ${target.name}.`);}
  function heal(){persist(players.map((p)=>p.id===target.id?{...p,energy:100}:p));setMessage(`${target.name} vuelve al 100% de energía.`);}
  function award(){persist(players.map((p)=>p.id===target.id?{...p,tokens:p.tokens+2}:p));setMessage(`+2 tokens de Arena para ${target.name}.`);}
  function linkTeammate(found:Player){setTeamMate(found.id);setMessage(`Invitación enviada a ${found.name}. Podéis jugar juntos.`);if(supabase&&active.dbId&&found.dbId)void supabase.from("team_invites").insert({from_player_id:active.dbId,to_player_id:found.dbId,station_id:pendingStation?.id??null,status:"pending"});}
  function handleScannedValue(value:string){ const urlValue=value.trim(); let code=urlValue; try { const url=new URL(urlValue); const params=url.searchParams; const player=params.get("player"); const route=params.get("qr"); if(player){setPlayerCardCode(player);setMessage("Tarjeta de entrenador detectada. Úsala en Team Rocket o Arena de Payá.");closeCamera();return;} code=route||urlValue; } catch {} const found=stations.find((item)=>item.id===code.toLowerCase()); if(found){closeCamera();startStation(found);} else setMessage("Este QR no pertenece a la Liga."); }
  async function openCamera(){
    try { const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false}); if(videoRef.current){videoRef.current.srcObject=stream; await videoRef.current.play();} setCameraOpen(true); const Detector=(window as unknown as {BarcodeDetector?:new (options:{formats:string[]})=>{detect:(source:HTMLVideoElement)=>Promise<{rawValue:string}[]>}}).BarcodeDetector; if(Detector){ const detector=new Detector({formats:["qr_code"]}); const read=async()=>{if(!videoRef.current)return; try{const found=await detector.detect(videoRef.current);if(found[0]?.rawValue){handleScannedValue(found[0].rawValue);return;}}catch{} scanTimerRef.current=window.setTimeout(read,450);}; read();} else setMessage("Tu navegador no permite lectura automática. Puedes escribir el código de debajo del QR."); }
    catch { setMessage("No se ha podido abrir la cámara. Usa el código escrito."); }
  }
  function closeCamera(){if(scanTimerRef.current)window.clearTimeout(scanTimerRef.current);scanTimerRef.current=null;const stream=videoRef.current?.srcObject as MediaStream | null;stream?.getTracks().forEach((track)=>track.stop());if(videoRef.current)videoRef.current.srcObject=null;setCameraOpen(false);}
  if(!loaded)return null;

  return <main className="app-shell"><header className="topbar"><button className="wordmark" onClick={()=>setScreen(activeId?(isOpen?"home":"waiting"):"select")}><span className="ball-mark">◓</span> NIVEL <em>27</em></button>{activeId&&<button className="admin-link" onClick={()=>setScreen("select")}>Cambiar perfil</button>}</header>
    {screen==="select"&&<section className="select-view"><img className="hero-eevee" src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png" alt="Eevee"/><p className="eyebrow">LIGA DE LA TERRAZA</p><h1>¿Quién eres?</h1><p>Elige tu perfil para entrar en la ruta.</p><div className="profile-grid">{players.map((player)=><button key={player.id} className="profile-choice" onClick={()=>{setActiveId(player.id);localStorage.setItem("liga27-active-player",player.id);setScreen(player.evolution?(isOpen?"home":"waiting"):"partner");}}><span>{player.name.slice(0,1)}</span><b>{player.name}</b><small>{player.id==="alejandro"?"Administrador":player.evolution??"Elige Eevee"}</small></button>)}</div></section>}
    {screen==="partner"&&<section className="partner-view"><button className="back" onClick={()=>setScreen("select")}>← Cambiar perfil</button><img className="hero-eevee" src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png" alt="Eevee"/><p className="eyebrow">TU PRIMERA DECISIÓN</p><h2>¿Hacia dónde evolucionará Eevee?</h2><p className="lead">Elige la afinidad de tu compañero. Evolucionará al conseguir cuatro capturas.</p><div className="evolution-grid">{eeveelutions.map((evo)=><button className="evolution-card" key={evo.name} onClick={()=>chooseEvolution(evo.name)}><img src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${evo.image}.png`} alt={evo.name}/><b>{evo.name}</b><span>Tipo {evo.type}</span><small>{evo.perk}</small></button>)}</div></section>}
    {screen==="waiting"&&<section className="waiting-view"><img className="hero-eevee" src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png" alt="Eevee"/><p className="eyebrow">LA LIGA TODAVÍA ESTÁ CERRADA</p><h1>Preparad<br/>vuestro equipo.</h1><p className="waiting-date">Sábado 29 de agosto · 17:00</p><div className="countdown">{([['Días',countdown.days],['Horas',countdown.hours],['Min',countdown.minutes],['Seg',countdown.seconds]] as const).map(([label,value])=><div key={label}><b>{String(value).padStart(2,'0')}</b><span>{label}</span></div>)}</div><article className="instructions-card"><b>Antes de que empiece</b><ol><li>Elige tu perfil.</li><li>Elige la evolución de Eevee.</li><li>El sábado se abrirán los QR de la terraza.</li></ol><p>La ruta completa lleva a Meseta Añil. Los tokens se canjean en la barra.</p></article><button className="change-evolution" onClick={()=>setScreen("partner")}>Cambiar Eeveelution</button>{active.id==="alejandro"&&<button className="admin-shortcut" onClick={()=>setScreen("admin")}>Abrir administración</button>}</section>}
    {screen==="evolution"&&<section className="evolution-scene"><p>¿Qué? ¡Eevee está evolucionando!</p><img src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${chosenEvolution?.image}.png`} alt={evolved}/><h1>¡{evolved} ha evolucionado!</h1><button onClick={()=>{patchActive({evolvedShown:true});setScreen("home");}}>Continuar</button></section>}
    {screen==="home"&&<section className="home-view">{TEST_MODE&&<div className="test-banner"><b>Modo pruebas activo</b><span>La Liga está abierta para probar todas las pantallas.</span></div>}<p className="eyebrow">ENTRENADOR/A · {active.name.toUpperCase()}</p><div className="profile-hero"><div className={`orb ${chosenEvolution?.type.toLowerCase()??""}`}><img src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${companionImage}.png`} alt={evolved}/></div><div><p className="muted">COMPAÑERO</p><h1>{evolved}</h1><p className="subline">Nivel {active.level} · {evolved==="Eevee"?`afinidad ${chosenEvolution?.type}`:`tipo ${chosenEvolution?.type}`}</p></div></div><div className="status-grid"><article className="status-card wide"><div><span>NIVEL {active.level}</span><strong>{active.xp%100}%</strong></div><div className="meter"><i style={{width:`${active.xp%100}%`}}/></div><small>{evolved==="Eevee"?"Evoluciona tras 4 capturas":"Progreso de entrenador"}</small></article><article className="status-card"><span>ENERGÍA</span><strong>{active.energy}%</strong><div className="meter energy"><i style={{width:`${active.energy}%`}}/></div></article><article className="status-card"><span>TOKENS</span><strong>{active.tokens}</strong><small>para la barra</small></article></div><button className="scan-cta" onClick={()=>setScreen("scan")}><b>◉</b><span>Escanear QR</span><small>Ruta {complete}/12</small></button><div className="bottom-nav"><button onClick={()=>setScreen("home")}>●<span>Perfil</span></button><button onClick={()=>setScreen("pokedex")}>▦<span>Pokédex</span></button><button className="scan-nav" onClick={()=>setScreen("scan")}>⌁<span>Escanear</span></button><button onClick={()=>setScreen("route")}>☰<span>Ruta</span></button></div>{active.id==="alejandro"&&<button className="admin-shortcut" onClick={()=>setScreen("admin")}>Centro Pokémon · administración</button>}{message&&<p className="toast">{message}</p>}</section>}
    {screen==="pokedex"&&<section className="panel-view"><button className="back" onClick={()=>setScreen("home")}>← Volver</button><p className="eyebrow">TU POKÉDEX</p><h2>Capturas reales</h2><p className="lead">Cada victoria revela un Pokémon aleatorio. Puedes conservarlo o canjearlo por tokens en cualquier momento.</p><div className="capture-grid">{active.captures.length?active.captures.map((capture,index)=><article className={`dex-card ${capture.rarity.toLowerCase()}`} key={`${capture.id}-${index}`}><img src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${capture.sprite}.png`} alt={capture.name}/><span>#{String(capture.id).padStart(3,"0")} · {capture.rarity}</span><b>{capture.name}</b><button onClick={()=>cashCapture(index)}>Canjear · +{capture.value} token{capture.value>1?"s":""}</button></article>):<div className="empty-dex"><img src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png" alt="Eevee"/><b>Aún no hay capturas</b><small>Escanea un QR de entrenador para empezar.</small></div>}</div>{message&&<p className="toast">{message}</p>}</section>}
    {screen==="scan"&&<section className="panel-view scan-view"><button className="back" onClick={()=>{closeCamera();setScreen("home");}}>← Volver</button><p className="eyebrow">ESCÁNER</p><h2>Encuentra un QR</h2><div className="camera-box">{cameraOpen?<video ref={videoRef} playsInline muted/>:<><span>⌁</span><b>Escanea un código</b><small>Usa la cámara de tu móvil.</small></>}<button className="camera-button" onClick={cameraOpen?closeCamera:openCamera}>{cameraOpen?"Cerrar cámara":"Abrir cámara"}</button></div><p className="or">o introduce el código</p><div className="code-entry"><input value={manualCode} onChange={(e)=>setManualCode(e.target.value)} placeholder="Ej. trainer-1"/><button onClick={()=>{const found=stations.find((item)=>item.id===manualCode.trim().toLowerCase());if(found){closeCamera();startStation(found);}else setMessage("Código no encontrado.");}}>Continuar</button></div><p className="hint">Prueba: trainer-1 a trainer-8, rocket-1 a rocket-4.</p>{message&&<p className="toast">{message}</p>}</section>}
    {screen==="route"&&<section className="panel-view"><button className="back" onClick={()=>setScreen("home")}>← Volver</button><p className="eyebrow">REGIÓN DE KANTO · RUTA OBLIGATORIA</p><h2>Camino a Meseta Añil</h2><p className="lead">Un mapa inspirado en Kanto. Pasa por los 12 QR: cada punto marca una ciudad, un gimnasio o una emboscada Rocket.</p><div className="kanto-region"><div className="ocean-label">MAR DE KANTO</div><div className="pallet town">Pueblo<br/>Paleta</div>{journeyIds.map((id,index)=>{const item=stations.find((station)=>station.id===id)!;const done=active.route.includes(id);return <button onClick={()=>startStation(item)} key={id} className={`kanto-pin pin-${index+1} ${item.kind} ${done?"complete":""}`}><i>{done?"✓":item.kind==="rocket"?"R":String(index+1)}</i><b>{item.title}</b><small>{item.kind==="rocket"?"Team Rocket":item.area}</small></button>})}<div className={`indigo-pin ${finalUnlocked?"unlocked":""}`}><i>★</i><b>Meseta Añil</b><small>{finalUnlocked?"Alto Mando listo":"12 insignias necesarias"}</small></div><div className="route-line line-a"/><div className="route-line line-b"/><div className="route-line line-c"/></div></section>}
    {screen==="arena"&&<section className="panel-view arena-view"><button className="back" onClick={()=>{setPendingStation(null);setScreen("home")}}>← Volver</button><p className="eyebrow">✦ ARENA DE PAYÁ {pendingStation?"· ENCUENTRO PREVIO":"· RETO LIBRE"}</p><h2>{pendingStation?"Antes del gimnasio…":"Reta a un entrenador"}</h2><p className="lead">{pendingStation?`Payá ha aparecido antes de ${pendingStation.title}. Forma equipo o reta a alguien antes de seguir.`:"Escanea la tarjeta de tu contrincante, elegid el reto y acudid a Alejandro. El ganador recibe +2 tokens."}</p><div className="card-scanner"><span>▣</span><div><b>Tarjeta de entrenador</b><small>Escanea su QR o escribe el código del jugador.</small></div></div><div className="code-entry"><input value={playerCardCode} onChange={(e)=>setPlayerCardCode(e.target.value)} placeholder="Ej. jugador-4"/><button onClick={()=>{const found=players.find(p=>p.id===playerCardCode.trim().toLowerCase());if(found&&found.id!==active.id){setArenaOpponent(found.id);setMessage(`Tarjeta de ${found.name} enlazada.`);}else setMessage("Tarjeta no válida o es tu propio perfil.")}}>Enlazar</button></div>{arenaOpponent&&<div className="opponent-found"><span>VS</span><b>{active.name}</b><i>contra</i><b>{players.find(p=>p.id===arenaOpponent)?.name}</b></div>}<div className="arena-cards">{["Farmeo de aura","Chiste malo","Cata a ciegas","Venta imposible","Imitación express","Duelo de karaoke","Pulso de dedos"].map((challenge)=><button className={arenaChallenge===challenge?"chosen":""} key={challenge} onClick={()=>setArenaChallenge(challenge)}>{challenge}<span>Ganador: +2 tokens</span></button>)}</div><button className="arena-confirm" onClick={beginArena}>{pendingStation?"Resolver encuentro y seguir":"Confirmar reto en la Arena"}</button>{message&&<p className="toast">{message}</p>}</section>}
    {screen==="team"&&<section className="panel-view team-view"><button className="back" onClick={()=>{setPendingStation(null);setScreen("home")}}>← Volver</button><p className="eyebrow">R ENEMIGO · MISIÓN COOPERATIVA</p><h2>Team Rocket os espera</h2><p className="lead">Escanea la tarjeta QR de otra persona. Le llegará la invitación al abrir su tarjeta; si no está disponible, puede ayudarte desde fuera y tú completas el combate.</p><div className="rocket-banner"><img src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/52.png" alt="Meowth"/><b>¡Preparad un equipo de dos!</b><span>Recomendado · no obligatorio</span></div><div className="code-entry"><input value={playerCardCode} onChange={(e)=>setPlayerCardCode(e.target.value)} placeholder="Código de su tarjeta, ej. jugador-6"/><button onClick={()=>{const found=players.find(p=>p.id===playerCardCode.trim().toLowerCase());if(found&&found.id!==active.id){setTeamMate(found.id);setMessage(`Invitación enviada a ${found.name}. Podéis jugar juntos.`);}else setMessage("Tarjeta no válida o es tu propio perfil.")}}>Escanear</button></div>{teamMate&&<div className="opponent-found team-ok"><span>R</span><b>{active.name}</b><i>con</i><b>{players.find(p=>p.id===teamMate)?.name}</b></div>}<button className="arena-confirm" onClick={()=>{const go=pendingStation;setPendingStation(null);setScreen("home");if(go){setAnswer(null);setMessage("");setStation(go);}}}>{teamMate?"Entrar juntos en la guarida":"Jugar con ayuda externa"}</button>{message&&<p className="toast">{message}</p>}</section>}
    {screen==="admin"&&<section className="panel-view admin-view"><button className="back" onClick={()=>setScreen(isOpen?"home":"waiting")}>← Salir de administración</button><p className="eyebrow">PANEL DE ALEJANDRO · DIRECCIÓN DE JUEGO</p><h2>Entrenadores</h2><p className="lead">Aquí puedes consultar y corregir la evolución elegida por cada persona antes de que se abra la Liga.</p><div className="admin-roster">{players.filter((player)=>player.id!=="alejandro").map((player)=>{const evo=eeveelutions.find((item)=>item.name===player.evolution);return <article key={player.id} className="roster-row"><img src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${evo?.image??"133"}.png`} alt={evo?.name??"Eevee"}/><div><b>{player.name}</b><small>{evo?`${evo.name} · ${evo.type}`:"Aún no ha elegido"}</small></div><select aria-label={`Evolución de ${player.name}`} value={player.evolution??""} onChange={(e)=>e.target.value&&setPlayerEvolution(player.id,e.target.value as Evolution)}><option value="">Sin elegir</option>{eeveelutions.map((item)=><option key={item.name} value={item.name}>{item.name}</option>)}</select></article>})}</div><h3>Centro Pokémon y barra</h3><select className="large-select" value={adminTarget} onChange={(e)=>setAdminTarget(e.target.value)}>{players.map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</select><article className="admin-player"><div className="mini-orb">◒</div><div><b>{target.name}</b><small>{target.tokens} tokens · energía {target.energy}% · ruta {target.route.length}/12</small></div></article><div className="admin-actions"><button onClick={heal}>Recuperar al 100%</button><button onClick={award}>Dar +1 por Arena</button></div><h3>Canjear en barra</h3><div className="menu-grid">{menu.map((item)=><button key={item.label} onClick={()=>redeem(item)}><b>{item.label}</b><span>{item.cost} tokens</span></button>)}</div>{message&&<p className="toast">{message}</p>}</section>}
    {station&&question&&isOpen&&<div className="modal-wrap"><section className="battle-modal classic-battle"><button className="close" onClick={()=>setStation(null)}>×</button><p className="eyebrow">{station.kind==="rocket"?"¡TEAM ROCKET QUIERE LUCHAR!":"¡UN ENTRENADOR TE DESAFÍA!"}</p><div className="enemy-field"><div className="hp-card"><b>{station.kind==="rocket"?"MEOWTH":"RIVAL"} <small>Nv. {difficulty+3}</small></b><div className="battle-hp"><i/></div></div><img src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${station.kind==="rocket"?52:25}.png`} alt="Pokémon rival"/></div><div className="player-field"><img src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/${companionImage}.png`} alt={evolved}/><div className="hp-card"><b>{evolved.toUpperCase()} <small>Nv. {active.level}</small></b><div className="battle-hp player-hp"><i style={{width:`${active.energy}%`}}/></div></div></div><p className="battle-copy">{message||`${evolved}, ¿qué harás?`}</p><p className="question">{question.prompt}</p><div className="answers">{question.options.map((option,index)=><button key={option} className={answer===index?"selected":""} onClick={()=>setAnswer(index)}><span>{["Impactrueno","Ataque rápido","Mordisco","Poder oculto"][index]}</span>{option}</button>)}</div><button className="answer-cta" disabled={answer===null||Boolean(message)} onClick={resolveBattle}>{message?"Resultado registrado":question.label}</button>{message&&<div className="result"><button onClick={()=>{const evolveNow=active.route.length===4&&Boolean(active.evolution)&&!active.evolvedShown;setStation(null);setMessage("");setScreen(evolveNow?"evolution":"home");}}>Continuar</button></div>}</section></div>}
  </main>;
}
