import type { Question } from "./types";

export const QUESTION_BANK: Question[] = [
  { id: "general-01", category: "general", question: "¿Qué país fue el primero en reconocer el sufragio femenino a nivel nacional?", options: ["Reino Unido", "Nueva Zelanda", "Estados Unidos", "Finlandia"], correctAnswer: 1 },
  { id: "general-02", category: "general", question: "¿Cuál es el único continente sin un desierto cálido?", options: ["Europa", "América del Sur", "Asia", "Antártida"], correctAnswer: 0 },
  { id: "general-03", category: "general", question: "¿Qué elemento químico tiene el símbolo W?", options: ["Wolframio", "Wolframita", "Titanio", "Zinc"], correctAnswer: 0 },
  { id: "general-04", category: "general", question: "¿En qué año cayó Constantinopla en manos del Imperio otomano?", options: ["1492", "1453", "1517", "1412"], correctAnswer: 1 },
  { id: "general-05", category: "general", question: "¿Qué filósofo escribió “Crítica de la razón pura”?", options: ["Friedrich Nietzsche", "René Descartes", "Immanuel Kant", "Georg Hegel"], correctAnswer: 2 },
  { id: "general-06", category: "general", question: "¿Cuál es la capital constitucional de Bolivia?", options: ["La Paz", "Santa Cruz", "Sucre", "Cochabamba"], correctAnswer: 2 },
  { id: "general-07", category: "general", question: "¿Qué científico formuló el principio de incertidumbre?", options: ["Albert Einstein", "Niels Bohr", "Max Planck", "Werner Heisenberg"], correctAnswer: 3 },
  { id: "general-08", category: "general", question: "¿Cuál de estas obras NO fue escrita por William Shakespeare?", options: ["Macbeth", "Hamlet", "Fausto", "Otelo"], correctAnswer: 2 },
  { id: "general-09", category: "general", question: "¿Cuál es el hueso más pequeño del cuerpo humano?", options: ["Estribo", "Yunque", "Martillo", "Hioides"], correctAnswer: 0 },
  { id: "general-10", category: "general", question: "¿Qué civilización construyó la ciudad de Petra?", options: ["Egipcios", "Nabateos", "Romanos", "Fenicios"], correctAnswer: 1 },
  { id: "general-11", category: "general", question: "¿Qué país tiene más husos horarios si se cuentan sus territorios de ultramar?", options: ["Rusia", "Estados Unidos", "Francia", "China"], correctAnswer: 2 },
  { id: "general-12", category: "general", question: "¿Cuál es la montaña más alta de Europa según la mayoría de clasificaciones geográficas modernas?", options: ["Mont Blanc", "Matterhorn", "Monte Elbrús", "Monte Olimpo"], correctAnswer: 2 },
  { id: "general-13", category: "general", question: "¿Qué compositor continuó trabajando después de quedarse prácticamente sordo?", options: ["Mozart", "Beethoven", "Bach", "Chopin"], correctAnswer: 1 },
  { id: "general-14", category: "general", question: "¿Qué planeta del Sistema Solar tiene el día más largo?", options: ["Venus", "Mercurio", "Marte", "Saturno"], correctAnswer: 0 },
  { id: "general-15", category: "general", question: "¿Qué escritor creó al detective Hercule Poirot?", options: ["Arthur Conan Doyle", "Agatha Christie", "Edgar Allan Poe", "Raymond Chandler"], correctAnswer: 1 },
  { id: "general-16", category: "general", question: "¿Qué órgano del cuerpo humano produce la insulina?", options: ["Hígado", "Riñón", "Páncreas", "Bazo"], correctAnswer: 2 },
  { id: "general-17", category: "general", question: "¿En qué país se encuentra Transilvania?", options: ["Hungría", "Rumanía", "Bulgaria", "Serbia"], correctAnswer: 1 },
  { id: "general-18", category: "general", question: "¿Qué batalla marcó la derrota definitiva de Napoleón Bonaparte?", options: ["Trafalgar", "Austerlitz", "Waterloo", "Leipzig"], correctAnswer: 2 },
  { id: "general-19", category: "general", question: "¿Qué idioma tiene más hablantes nativos del mundo?", options: ["Inglés", "Español", "Hindi", "Chino mandarín"], correctAnswer: 3 },
  { id: "general-20", category: "general", question: "¿Cuál es el océano más profundo del planeta?", options: ["Atlántico", "Índico", "Pacífico", "Ártico"], correctAnswer: 2 },
  { id: "general-21", category: "general", question: "¿Qué pintor español es conocido por su obra “Las meninas”?", options: ["Goya", "Picasso", "Velázquez", "El Greco"], correctAnswer: 2 },
  { id: "general-22", category: "general", question: "¿Qué país vendió Alaska a Estados Unidos en 1867?", options: ["Reino Unido", "Francia", "Canadá", "Rusia"], correctAnswer: 3 },
  { id: "general-23", category: "general", question: "¿Qué significa literalmente “Memento mori”?", options: ["Vive el presente", "Recuerda que morirás", "Todo pasa", "El tiempo vuela"], correctAnswer: 1 },
  { id: "general-24", category: "general", question: "¿Cuál de estos animales NO tiene corazón?", options: ["Medusa", "Pulpo", "Estrella de mar", "Calamar"], correctAnswer: 0 },
  { id: "general-25", category: "general", question: "¿Qué ciudad fue sepultada por la erupción del Vesubio en el año 79?", options: ["Pompeya", "Roma", "Atenas", "Cartago"], correctAnswer: 0 },
  { id: "general-26", category: "general", question: "¿Cuántos pares de cromosomas tiene normalmente un ser humano?", options: ["21", "23", "24", "46"], correctAnswer: 1 },
  { id: "general-27", category: "general", question: "¿Qué país tiene la mayor cantidad de volcanes activos del mundo?", options: ["Japón", "Islandia", "Indonesia", "Italia"], correctAnswer: 2 },
  { id: "general-28", category: "general", question: "¿Quién escribió “El contrato social”?", options: ["Voltaire", "Rousseau", "Montesquieu", "Hobbes"], correctAnswer: 1 },
  { id: "general-29", category: "general", question: "¿Cuál es el metal más abundante en la corteza terrestre?", options: ["Hierro", "Cobre", "Aluminio", "Oro"], correctAnswer: 2 },
  { id: "general-30", category: "general", question: "¿Qué número es considerado un número perfecto?", options: ["12", "28", "18", "24"], correctAnswer: 1 },
  { id: "trick-01", category: "trick", question: "Si un gallo pone un huevo en la frontera entre España y Portugal, ¿de quién es el huevo?", options: ["De España", "De Portugal", "De ambos países", "Los gallos no ponen huevos"], correctAnswer: 3 },
  { id: "trick-02", category: "trick", question: "¿Qué pesa más: un kilo de plomo o un kilo de plumas?", options: ["El plomo", "Las plumas", "Pesan lo mismo", "Depende de dónde los peses"], correctAnswer: 2 },
  { id: "trick-03", category: "trick", question: "Si adelantas al segundo corredor de una carrera, ¿en qué posición quedas?", options: ["Primero", "Segundo", "Tercero", "Depende de la carrera"], correctAnswer: 1 },
  { id: "trick-04", category: "trick", question: "¿Cuántos animales de cada especie metió Moisés en el arca?", options: ["Dos", "Cuatro", "Uno", "Ninguno, fue Noé"], correctAnswer: 3 },
  { id: "trick-05", category: "trick", question: "Un avión se estrella justo en la frontera entre dos países. ¿Dónde entierran a los supervivientes?", options: ["En el primer país", "En el segundo", "En ambos", "No se entierra a los supervivientes"], correctAnswer: 3 },
  { id: "trick-06", category: "trick", question: "¿Qué mes tiene 28 días?", options: ["Febrero", "Todos", "Enero y febrero", "Ninguno"], correctAnswer: 1 },
  { id: "trick-07", category: "trick", question: "Si tienes 3 manzanas y coges 2, ¿cuántas tienes?", options: ["1", "2", "3", "5"], correctAnswer: 1 },
  { id: "trick-08", category: "trick", question: "¿Qué es lo primero que haces al levantarte?", options: ["Desayunar", "Abrir los ojos", "Mirar el móvil", "Quejarte"], correctAnswer: 1 },
  { id: "trick-09", category: "trick", question: "¿Cuántos cumpleaños tiene una persona normalmente?", options: ["Uno", "Tantos como años tenga", "Dos", "365"], correctAnswer: 0 },
  { id: "trick-10", category: "trick", question: "Un padre y su hijo tienen un accidente. El padre muere y el hijo llega al hospital. El cirujano dice: “No puedo operarlo, es mi hijo”. ¿Quién es?", options: ["Su padrastro", "Su tío", "Su madre", "Un error, no tiene sentido"], correctAnswer: 2 },
  { id: "trick-11", category: "trick", question: "¿Qué puedes romper sin tocarlo?", options: ["Una ventana", "Un récord", "Una piedra", "Una mesa"], correctAnswer: 1 },
  { id: "trick-12", category: "trick", question: "¿Cuántas veces puedes restarle 10 a 100?", options: ["10 veces", "9 veces", "Una vez", "Infinitas"], correctAnswer: 2 },
  { id: "trick-13", category: "trick", question: "¿Qué sube pero nunca baja?", options: ["La temperatura", "Tu edad", "Un ascensor", "El precio de la gasolina"], correctAnswer: 1 },
  { id: "trick-14", category: "trick", question: "¿Qué tiene dientes pero no puede morder?", options: ["Un tiburón", "Una cremallera", "Un peine", "Un político"], correctAnswer: 2 },
  { id: "trick-15", category: "trick", question: "Si una persona vive en el piso 20 de un edificio y todos los días baja en ascensor hasta la calle, pero al volver solo sube hasta el 10 y camina el resto, ¿por qué?", options: ["Está haciendo deporte", "El ascensor está roto", "Es bajita y no llega al botón 20", "Tiene miedo a las alturas"], correctAnswer: 2 },
  { id: "trick-16", category: "trick", question: "¿Qué palabra está siempre escrita incorrectamente en el diccionario?", options: ["Incorrectamente", "Diccionario", "Ortografía", "Nunca"], correctAnswer: 0 },
  { id: "trick-17", category: "trick", question: "¿Qué tiene cuello pero no cabeza?", options: ["Una botella", "Una jirafa", "Una camisa", "Una persona dormida"], correctAnswer: 0 },
  { id: "trick-18", category: "trick", question: "Si tardas 10 minutos en cocinar un huevo, ¿cuánto tardas en cocinar 5 huevos a la vez?", options: ["50 minutos", "25 minutos", "10 minutos", "5 minutos"], correctAnswer: 2 },
  { id: "trick-19", category: "trick", question: "¿Qué tiene ciudades, ríos y montañas, pero no tiene personas, agua ni árboles?", options: ["Un planeta", "Un mapa", "Un videojuego", "Una fotografía"], correctAnswer: 1 },
  { id: "trick-20", category: "trick", question: "¿Qué es negro cuando está limpio y blanco cuando está sucio?", options: ["Un calcetín", "Una pizarra", "Un coche", "Una camiseta"], correctAnswer: 1 },
  { id: "trick-21", category: "trick", question: "Si un tren eléctrico viaja hacia el norte y el viento sopla hacia el sur, ¿hacia dónde va el humo?", options: ["Norte", "Sur", "Este", "No hay humo"], correctAnswer: 3 },
  { id: "trick-22", category: "trick", question: "¿Qué tiene una cara y dos manos, pero no puede aplaudir?", options: ["Un reloj", "Un mimo", "Una estatua", "Un muñeco"], correctAnswer: 0 },
  { id: "trick-23", category: "trick", question: "¿Qué tiene muchos agujeros pero puede contener agua?", options: ["Una esponja", "Un colador", "Un queso", "Un queso gruyere gigante"], correctAnswer: 0 },
  { id: "trick-24", category: "trick", question: "¿Qué puedes sostener con la mano izquierda, pero nunca con la derecha?", options: ["Tu mano derecha", "Un bolígrafo", "Una pelota", "Tu mano izquierda"], correctAnswer: 0 },
  { id: "trick-25", category: "trick", question: "Un hombre sale bajo una lluvia intensa sin paraguas, sin gorro y sin cubrirse. No se moja ni un solo pelo. ¿Cómo?", options: ["Está bajo techo", "Es calvo", "Corre muy rápido", "Lleva peluca"], correctAnswer: 1 },
  { id: "trick-26", category: "trick", question: "¿Qué aparece una vez en un minuto, dos veces en un momento y nunca en cien años?", options: ["La letra M", "La letra A", "La letra E", "La letra O"], correctAnswer: 0 },
  { id: "trick-27", category: "trick", question: "Si una casa tiene cuatro paredes orientadas al sur y pasa un oso por delante, ¿de qué color es?", options: ["Marrón", "Negro", "Blanco", "Depende del oso"], correctAnswer: 2 },
  { id: "trick-28", category: "trick", question: "¿Qué pregunta nunca puedes responder con “sí”?", options: ["¿Estás despierto?", "¿Estás dormido?", "¿Quieres comer?", "¿Eres humano?"], correctAnswer: 1 },
  { id: "trick-29", category: "trick", question: "Si tienes una cerilla y entras en una habitación oscura donde hay una vela, una lámpara de aceite y una chimenea, ¿qué enciendes primero?", options: ["La vela", "La lámpara", "La chimenea", "La cerilla"], correctAnswer: 3 },
  { id: "trick-30", category: "trick", question: "¿Qué tiene 13 corazones y ningún órgano?", options: ["Un monstruo", "Una baraja de cartas", "Un pulpo", "Un ser humano muy raro"], correctAnswer: 1 },
];
